# write_pdf.py
from langchain_core.tools import tool
from datetime import datetime
from pathlib import Path
import subprocess
import shutil
from graphviz import Digraph
import re

def latex_escape(text: str) -> str:
    """
    Escape special LaTeX characters to avoid compilation errors.
    """
    if not text:
        return ""

    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
        '\\': r'\textbackslash{}'
    }

    regex = re.compile('|'.join(re.escape(key) for key in replacements.keys()))
    return regex.sub(lambda match: replacements[match.group()], text)


@tool
def render_latex_pdf(latex_content: str, flowchart_steps: list[str] = None) -> str:
    """
    Render a LaTeX document to PDF using Tectonic with optional methodology flowchart.

    Args:
        latex_content: The main content of the LaTeX paper
        flowchart_steps: Optional list of steps for a methodology flowchart

    Returns:
        Path to the generated PDF document
    """
    if shutil.which("tectonic") is None:
        raise RuntimeError("Tectonic is not installed. Install it first on your system.")

    try:
        # Step 1: Create output directory
        output_dir = Path("output").absolute()
        output_dir.mkdir(exist_ok=True)

        # Step 2: Setup timestamped filenames
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        tex_file = output_dir / f"paper_{timestamp}.tex"

        # Step 3: Generate flowchart if steps are provided
        flowchart_file = None
        if flowchart_steps:
            dot = Digraph(comment="Methodology Flowchart")
            for i, step in enumerate(flowchart_steps, 1):
                dot.node(f"Step{i}", latex_escape(step))
            for i in range(1, len(flowchart_steps)):
                dot.edge(f"Step{i}", f"Step{i+1}")
            flowchart_file = output_dir / f"methodology_{timestamp}.png"
            # Render PNG of flowchart
            dot.render(str(flowchart_file.with_suffix('')), format="png", cleanup=True)

        # Step 4: Escape main text
        safe_text = latex_escape(latex_content)

        # Step 5: Create LaTeX content with optional flowchart
        final_latex = r"""
\documentclass{article}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{geometry}
\geometry{margin=1in}
\title{Generated Research Paper}
\date{\today}
\begin{document}
\maketitle

\section*{Abstract}
{{ abstract }}

\section*{Full Paper}
{{ full_text }}

{% if flowchart_file %}
\section*{Methodology Flowchart}
\begin{center}
\includegraphics[width=0.8\textwidth]{{ flowchart_file }}
\end{center}
{% endif %}

\end{document}
        """

        # Simple replacement for abstract, full text, and flowchart
        final_latex = final_latex.replace("{{ abstract }}", safe_text[:500])
        final_latex = final_latex.replace("{{ full_text }}", safe_text)
        final_latex = final_latex.replace(
            "{{ flowchart_file }}", flowchart_file.name if flowchart_file else ""
        )

        tex_file.write_text(final_latex, encoding="utf-8")

        # Step 6: Compile with Tectonic
        result = subprocess.run(
            ["tectonic", tex_file.name, "--outdir", str(output_dir)],
            cwd=output_dir,
            capture_output=True,
            text=True,
        )

        # Step 7: Locate the generated PDF
        pdf_file = tex_file.with_suffix(".pdf")
        if not pdf_file.exists():
            print(f"Tectonic stdout:\n{result.stdout}")
            print(f"Tectonic stderr:\n{result.stderr}")
            raise FileNotFoundError("PDF file was not generated by Tectonic")

        print(f"Successfully generated PDF at {pdf_file}")
        return str(pdf_file)

    except Exception as e:
        print(f"Error rendering LaTeX: {str(e)}")
        raise
